add LegacyNewsCard
t3n/react-packages pull request #330
Opened 2020-11-13 08:08 UTC by hannesheyden

2020-11-13 09:39 UTC, johannessteu commented
Vllt auch in dem Legacy Ordner packen?

2020-11-13 09:40 UTC, hannesheyden commented
ja, bin da eh noch dran 👍

2020-11-17 11:30 UTC, itscursedphil requested changes

2020-11-17 11:30 UTC, itscursedphil commented on packages/components/src/LegacyNewsCard/LegacyNewsCard.tsx
> +const LegacyNewsCardHeadline = styled(Heading)<{ hero?: boolean }>`
Pick dir mal an solchen Stellen lieber den Type aus dem Interface: 
`const LegacyNewsCardHeadline = styled(Heading)<Pick<LegacyNewsCardProps, 'hero'>>`

2020-11-17 11:30 UTC, itscursedphil commented on packages/components/src/LegacyNewsCard/LegacyNewsCard.tsx
> +          position={hero ? 'static' : 'absolute'}
Warum willst du hier etwas `static` positionieren?

2020-11-17 11:30 UTC, itscursedphil commented on packages/components/src/LegacyNewsCard/LegacyNewsCard.tsx
> +  <LegacyMobileNewsCard display={['block', 'block', 'none']} px={3}>
Reich mal das Display lieber aus der Komponente darüber durch, oder noch besser, leg einfach eine Box in der Komponente darüber drum, sodass es gar nicht Teil der Komponente ist.

2020-11-17 11:31 UTC, itscursedphil requested changes

2020-11-17 11:31 UTC, itscursedphil commented on packages/components/src/LegacyNewsCard/LegacyNewsCard.tsx
> +export interface LegacyHeroCardProps {
Das Interface hier wird nirgends genutzt, oder?

2020-11-18 10:01 UTC, hannesheyden commented on packages/components/src/LegacyNewsCard/LegacyNewsCard.tsx
> +export interface LegacyHeroCardProps {
true, ist raus

2020-11-18 10:04 UTC, hannesheyden commented on packages/components/src/LegacyNewsCard/LegacyNewsCard.tsx
> +          position={hero ? 'static' : 'absolute'}
weil static der default position value von einem div ist. Habs jetzt aber auf initial geändert. Sollte am Ende aufs Gleiche hinauskommen 👍

2020-11-18 10:04 UTC, hannesheyden commented on packages/components/src/LegacyNewsCard/LegacyNewsCard.tsx
> +const LegacyNewsCardHeadline = styled(Heading)<{ hero?: boolean }>`
done

2020-11-18 10:22 UTC, itscursedphil requested changes

2020-11-18 10:22 UTC, itscursedphil commented on packages/components/src/LegacyNewsCard/LegacyNewsCard.tsx
> +          <LegacyLoadingHeroCard />
Soll die `LegacyLoadingHeroCard ` hier zwei mal auftauchen?

2020-11-18 10:24 UTC, hannesheyden commented on packages/components/src/LegacyNewsCard/LegacyNewsCard.tsx
> +          <LegacyLoadingHeroCard />
removed

2020-11-18 10:24 UTC, itscursedphil submitted a review, later dismissed

2020-11-18 12:14 UTC, itscursedphil approved these changes

2020-11-18 12:15 UTC, merged