WIP add SelectBox component
t3n/react-packages pull request #468
Opened 2021-02-17 12:59 UTC by birterohden

contributes to #TECHNIK-10492

2021-02-17 13:11 UTC, birterohden commented
Hier fehlt noch der Blick von Melanie - aber prinzipiell könnt ihr gerne schon rüberschauen 👀

2021-02-17 13:36 UTC, itscursedphil commented
Mega! Habe mir die Vorschau gerade einmal angeschaut. Dabei ist mir aufgefallen, dass der ausgewählte Wert farblich falsch dargestellt wird, wenn man das Dropdown noch einmal öffnet: 
<img width="535" alt="Screenshot 2021-02-17 at 14 33 13" src="https://user-images.githubusercontent.com/11021915/108211819-75473500-712d-11eb-856b-0b98d1c89836.png">

2021-02-17 14:54 UTC, itscursedphil requested changes

2021-02-17 14:54 UTC, itscursedphil commented on packages/components/src/SelectBox/SelectBox.tsx
> +const getCustomStyles = (error: boolean) => ({
Kannst du das hier noch so umschreiben, dass wir das Theme nicht direkt einbinden, sondern über den Hook übergeben? Können wir uns auch gern kurz zusammen anschauen wenn du dir nicht sicher bist, wie ich das meine!

2021-02-17 15:02 UTC, birterohden commented on packages/components/src/SelectBox/SelectBox.tsx
> +const getCustomStyles = (error: boolean) => ({
Schaue ich mir morgen früh an und melde mich, wenn ich da nicht weiterkomme :) Danke!

2021-02-18 15:02 UTC, birterohden commented on packages/components/src/SelectBox/SelectBox.tsx
> +const getCustomStyles = (error: boolean) => ({
Hab versucht das umzusetzen, schau gerne mal, ob ich das richtig gemacht habe 😅 Bin jetzt für die Woche erstmal raus.

2021-02-18 15:05 UTC, itscursedphil commented on packages/components/src/SelectBox/SelectBox.tsx
> +const getCustomStyles = (error: boolean) => ({
Ja sehr cool, so meinte ich das! Eine klitzekleine Kleinigkeit hab ich noch, aber kannst du dann am Montag auch einfach machen! :)

2021-02-18 15:06 UTC, itscursedphil requested changes

2021-02-18 15:06 UTC, itscursedphil commented on packages/components/src/SelectBox/SelectBox.tsx
> +const DropdownIndicator = (error: boolean, theme: Theme & DefaultTheme) => (
Kannst du die Funktion hier bitte in `createDropdownIndicator` oder so umbenennen? Die gibt ja nicht direkt eine React-Komponente zurück und braucht deshalb andere Properties.

2021-02-22 09:17 UTC, itscursedphil approved these changes

2021-02-22 09:26 UTC, merged